### ISSUE TITLE
Can't Install Via npm

### ISSUE THREAD

**Issue by soehlert** [ziishaned/wifi-password#1]
```
$ npm install -g wifi-pass
npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for wifi-pass
```

```
$ npm -v
6.4.1
```

```
System Software Overview:

System Version: macOS 10.14 (18A391)
```

**Comment by the4ndy** [comment]
correct me if i am wrong, but the curl method mentioned above does NOT work on Windows correct? The only option is NPM for windows? Or have you tested this on Bash for Windows (WSL)?

**Comment by ziishaned** [comment]
@the4ndy you need to install curl on windows or you can use npm. On windows 10 using Bash for Windows might work for you.

**Comment by ziishaned** [comment]
@soehlert I have published it on npm, now you can install it via npm install command.

```bash
npm i -g wifi-pass
```
